- name: Deletes the instances in b262-dev-network
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml
    
    - name: Remove the instance
      openstack.cloud.server:
        name: b262-dev-network
        state: absent

